name: Run Tests on Release

on:
  release:
    types: [published]

jobs:
 test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: rayhan
          POSTGRES_PASSWORD: rayhan123
          POSTGRES_DB: tinyorm_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U rayhan" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test